name: deploy-tickets
on:
  push:
    branches:
      - master
    paths:
      - 'tickets/**' 
jobs:
  build:
    runs-on:  ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the image
        run:  cd tickets && docker build . --file Dockerfile --tag narimanr/tickets
      - name: Login to docker
        run:  docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASS }}
      - name: push to docker
        run:  docker push narimanr/tickets
