name: deploy-auth

on: 
  push:
    branches:
      - master
    paths:
      - 'auth/**'
      
jobs:
  build:
    runs-on: ubuntu-lastest
    steps:
      - uses: actions/checkout@v2
      - run:  cd auth && docker build -t narimanr/auth .
      - run:  docker login -u $DOCKER_USERNAME -p $DOCKER_PASS
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      - run: docker push narimanr/auth
