name: deploy-manifests
on:
  push:
    branches:
      - master
    paths:
      - 'infra/**' 
jobs:
  build:
    runs-on:  ubuntu-latest
    environment: Production
    steps:
      - uses: actions/checkout@v2
      - name: Login to Server and get context
        run:  doctl kubernetes cluster kubeconfig save ticketing
      - name: Apply updated manifest
        run: kubectl apply -f infra/k8s && kubectl apply -f infra/k8s-prod
